### ISSUE TITLE
styleUrls: ['./test.component.less'] doesn't seem to be working.

### ISSUE THREAD

**Issue by pachuka** [monounity/karma-typescript-angular2-transform#1]
Hello, I am using karma-typescript with the karma-typescript-angular2-transform. I have less file references in the styleUrls parameter when defining components, but it does not seem like the styles are ever incorporated into the final test. The html does seem to be applying correctly, so I am not sure what the issue is. I have attached my config below.

```javascript
module.exports = function (config) {
	config.set({

		// base path that will be used to resolve all patterns (eg. files, exclude)
		basePath: '',

		// frameworks to use
		// available frameworks: https://npmjs.org/browse/keyword/karma-adapter
		frameworks: ['jasmine', 'karma-typescript'],

		// list of files / patterns to load in the browser
		files: [
			{ pattern: "init-test-bed.spec.ts" },
			{ pattern: "src/**/*.+(ts|html)" }
		],

		// list of files to exclude
		exclude: [
		],

		// preprocess matching files before serving them to the browser
		// available preprocessors: https://npmjs.org/browse/keyword/karma-preprocessor
		preprocessors: {
			'**/*.ts': ['karma-typescript', 'sourcemap', 'coverage'],
		},

		coverageReporter: {
			reporters:
			[
				{ type: 'in-memory' },
				{ type: 'text-summary' }
			],
			includeAllSources: true
		},

		remapOptions: { basePath: './test' },

		karmaTypescriptConfig: {
			bundlerOptions: {
				entrypoints: /\.spec\.ts$/,
				transforms: [
					require('karma-typescript-angular2-transform'),
					require("karma-typescript-es6-transform")()
				]
			},
			compilerOptions: {
				lib: ['ES2015', 'DOM'],
				rootDir: './test'
			}
		},
		customLaunchers: {
			Chrome_with_debugging: {
				base: 'Chrome',
				flags: ['--remote-debugging-port=9222'],
				debug: true
			}
		},
		browserNoActivityTimeout: 100000,
		// test results reporter to use
		// possible values: 'dots', 'progress'
		// available reporters: https://npmjs.org/browse/keyword/karma-reporter
		reporters: ['mocha', 'karma-typescript', 'coverage'],


		// web server port
		port: 9876,


		// enable / disable colors in the output (reporters and logs)
		colors: true,


		// level of logging
		// possible values: config.LOG_DISABLE || config.LOG_ERROR || config.LOG_WARN || config.LOG_INFO || config.LOG_DEBUG
		logLevel: config.LOG_INFO,


		// enable / disable watching file and executing tests whenever any file changes
		autoWatch: true,


		// start these browsers
		// available browser launchers: https://npmjs.org/browse/keyword/karma-launcher
		browsers: ['Chrome'],


		// Continuous Integration mode
		// if true, Karma captures browsers, runs the tests and exits
		singleRun: false,

		// Concurrency level
		// how many browser should be started simultaneous
		concurrency: Infinity
	})
}
```
In the debug logs I do see angular2-transform.karma-typescript entries: 
Rewriting ./test.component.less to \base\src\test\test.component.less in C:/Sources/Workspaces/common/src/test/test.component.ts
Rewriting ./test.component.html to \base\src\test\test.component.html in C:/Sources/Workspaces/common/src/test/test.component.ts

Any ideas why the less isn't being compiled/included?

Running karma with the usual tsc && karma start, I am not using webpack to build this.

Thanks,
Piyush

**Comment by erikbarke** [comment]
Hey @pachuka, the raw contents of the less files should be bundled automatically, but karma-typescript doesn't compile less into css. If you want to compile less files, you can use the Transforms API, either by using [the PostCSS runner](https://github.com/monounity/karma-typescript-postcss-transform) with a less pugin, or an inline transform function which could run the less compiler or simply just mock the less/css needed for the test run. The Transforms API is documented in the [karma-typescript readme](https://github.com/monounity/karma-typescript/blob/master/README.md).

**Comment by pachuka** [comment]
@erikbarke, that actually makes a lot of sense, and I kind of had a gut feeling that was the case. Thanks for confirming it for me! I will play around with PostCSS (haven't used it before) and see if that works otherwise  mocking the less/css should be fine. Thanks again.
