### ISSUE TITLE
Doesn't transform urls defined with template literals

### ISSUE THREAD

**Issue by cleavera** [monounity/karma-typescript-angular2-transform#2]
If I define my templateUrl property using a template literal it doesn't get substituted.

```
@Component({
  selector: 'my-component',
  templateUrl: `./my-component.html`
})
```

Obviously I could just define as a string literal (and have done now). In this case I was converting an inline template to a templateUrl so the template literal quotes were already there. It took me an age to debug why it wasn't working.

It basically boils down to the following bit of code:
```
if (identifier.text === "templateUrl" &&
   property.initializer.kind === ts.SyntaxKind.StringLiteral) {

   rewriteUrl((<ts.StringLiteral> property.initializer));
}
```

To avoid confusion it should also allow `SyntaxKind.NoSubstitutionTemplateLiteral` or at least log some sort of warning so the user knows why the substitution isn't happening.

**Comment by erikbarke** [comment]
Hey @cleavera, of course! Would you like to add a check for `SyntaxKind.NoSubstitutionTemplateLiteral` in a PR?
