### ISSUE TITLE
Why is "base" hardcoded ?

### ISSUE THREAD

**Issue by Safiyya** [monounity/karma-typescript-angular2-transform#4]
Thanks for the library, it had made my life so much easier ! However, I'm struggling with something here : 

I'm receiving a `WARN [web-server]: 404: /base/src/app/components/workspace/workspace.component.html` when running my tests and then the test fails with `Failed: Uncaught (in promise): Failed to load src/app/components/workspace/workspace.component.html`

Here is my component : 
```
@Component({
    selector: "workspace",
    templateUrl: "workspace.component.html",
    styleUrls: ["./workspace.component.css"]
})
```

and my karma.config.js 
```
module.exports = function (config) {
    config.set({

        frameworks: ["jasmine", "fixture", "karma-typescript"],

        files: [
            { pattern: "base.spec.ts" },
            // Libraries
            { pattern: "https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js" },
            { pattern: "https://cdn.auth0.com/js/lock/10.8/lock.min.js" },
            // Envrionments
            { pattern: "src/environment/*.*" },
            // Application
            { pattern: "src/app/shared/**/*.*" },
            { pattern: "src/app/components/**/*.*" },
            // Specs
            { pattern: "src/test/specs/**/*.*" }
            
        ],

        jsonFixturesPreprocessor: {
            variableName: '__json__'
        },

        preprocessors: {
            "**/*.ts": ["karma-typescript"],
            '**/*.html': ['html2js'],
            '**/*.json': ['json_fixtures']
        },

        browserConsoleLogOptions: {
            terminal: true,
            level: ""
        },

        karmaTypescriptConfig: {
            bundlerOptions: {
                transforms: [
                    require("karma-typescript-angular2-transform"),
                    require("karma-typescript-es6-transform")()
                    
                ]
            },
            coverageOptions: {
                exclude: [/(\/src\/test\/.*|\.d|base.spec|\.spec)\.ts/i]
            },
            reports: {
                "html": {
                    "directory": "coverage",
                    "subdirectory": "html",
                    "filename": "index.html"
                },
                "lcovonly": {
                    "directory": "coverage",
                    "subdirectory": "lcov",
                    "filename": "lcov.info"
                }
            }
        },

        reporters: ["progress", "karma-typescript"],

        browsers: ["PhantomJS"]
    });
};

```

Debugging at the `transform.js` in this library, I can see line 29 : 
```
var url = path.join(context.config.karma.urlRoot, "base", relativeTemplateDir, unquotedString);
```
but I can't figure out why this is a hard-coded requirement ? 
The angular2 example in the karma-typescript code doesn't mention anything related to`base` and I'm lost on how to make this work.

**Comment by erikbarke** [comment]
The `base` part of the url is hardcoded because it's hardcoded [in the Karma middleware](https://github.com/karma-runner/karma/blob/master/lib/middleware/karma.js#L41) and you're not the only one [wondering why](https://github.com/karma-runner/karma/issues/1607).

Does the `html2js` preprocessor interfere somehow?

**Comment by Safiyya** [comment]
`html2js` definitely plays a role in this. After I removed it, all `404` errors disappeared but I have trouble running tests with `.html` fixtures now. 
Is there any configuration or file structure that you can recommend ? I'm trying to understand how  `proxies` could help or maybe find another fixtures loader.

**Comment by erikbarke** [comment]
You're processing **/*.html with html2js, does it work if you change that glob to something more specific, ie only the html files that need to be processed by html2js?

**Comment by Safiyya** [comment]
Yes that totally works, I should have thought about this ! Thanks for the speedy help.
